name: "GitHub Action for WeChat MiniProgram"
description: "A GitHub Action to automate deploying WeChat MiniProgram. Based on the miniprogram-ci."
author: "Crazy Urus"
branding:
  icon: package
  color: green
inputs:
  action_type:
    description: "Action type, preview or upload"
    required: false
    default: upload
  project_path:
    description: "Project path, which contains project.config.json"
    required: false
    default: "."
  page_path:
    description: "Page path, one of the pages in app.json"
    required: false
  page_query:
    description: "Page query"
    required: false
    default: ""
  scene:
    description: "Scene code"
    required: false
    default: 1011
  version:
    description: "Publish version"
    required: false
    default: 1.0.0
  description:
    description: "Release notes"
    required: false
outputs:
  preview_qrcode:
    description: "Preview the QR code of the MiniProgram"
runs:
  using: composite
  steps:
    - run: npm install pnpm -g
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: pnpm install --frozen-lockfile
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: npx ts-node --esm ./src/index.ts
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_ACTION_TYPE: ${{ inputs.action_type }}
        INPUT_PROJECT_PATH: ${{ inputs.project_path }}
        INPUT_PAGE_PATH: ${{ inputs.page_path }}
        INPUT_PAGE_QUERY: ${{ inputs.page_query }}
        INPUT_SCENE: ${{ inputs.scene }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_DESCRIPTION: ${{ inputs.description }}